### ISSUE TITLE
Questions about simplicity

### ISSUE THREAD

**Issue by junbeomlee** [ElementsProject/simplicity#1]
I heard your thesis and presentation very well. 
Thank you for giving me some great works!!

I have a question(I do not know much about functional languages). Simplicity says that there are more expressions than the bitcoin script. I wonder if there are any example of logic that bitcoin script can not express.

Thank you

**Comment by roconnor-blockstream** [comment]
This type of question is probably better suited for the mailing list or by personal email.

To answer it though, it may be the case that, in a purely theoretically sense, Bitcoin might be able to compute anything Simplicity can via enormous Bitcoin Scripts (and also ignoring Bitcoin Script's stack limitations), because one can probably simulate Boolean logical gates in Bitcoin Script.

I don't have any direct references at the moment, but I would like to build in Simplicity an example of validating certificates of illegal moves in the game of [Go](https://en.wikipedia.org/wiki/Go_(game)), which is something that I also wanted to do in [Elements](https://github.com/ElementsProject/elements) Script (similar to Bitcoin Script) but decided that without multiplication, it is too hard.

I can point you to the existing Simplicity program for Schnorr signature verification at https://github.com/ElementsProject/simplicity/blob/c66fc9c3efeebb067cbdcf1003286658a031d89d/Haskell/Simplicity/Programs/LibSecp256k1.hs#L702 as something that is probably infeasible to do in Bitcoin Script.  However this program probably wouldn't be directly deployed in Simplicity either, and instead we will use it as a specification of a Jet.

HTH.
